<?php
namespace Linkfire\Assignment\Models;

/**
 * Class Dog
 *  I tried making this model into a Phalcon MVC model, but I needed to set up a database.
 *  I'm sorry - i just don't know enough and can't super quickly find out how the database layer works.
 *  I have some stuff in index.php commented out where I tried.
 *
 *  In the end I ended up with the error "could not find driver" and I think that's because the pdo mysql driver
 *  Isn't included in the docker image and I didn't want to mess with it and have it break.
 */
class Dog /** extends Phalcon\Mvc\Model */
{
    private $id;
    private $name;
    private $weight;
    private $age;
    private $gender;
    private $isSuperCute = true;

    /**
     * @return mixed
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return float
     */
    public function getWeight(): float
    {
        return $this->weight;
    }

    /**
     * @param float $weight
     */
    public function setWeight(float $weight): void
    {
        $this->weight = $weight;
    }

    /**
     * @return int
     */
    public function getAge(): int
    {
        return $this->age;
    }

    /**
     * @param int $age
     */
    public function setAge(int $age): void
    {
        $this->age = $age;
    }

    /**
     * @return string
     */
    public function getGender(): string
    {
        return $this->gender;
    }

    /**
     * @param string $gender
     */
    public function setGender(string $gender): void
    {
        $this->gender = $gender;
    }

    /**
     * @return bool
     */
    public function isSuperCute(): bool
    {
        return $this->isSuperCute;
    }

    /**
     * @param bool $isSuperCute
     */
    public function setIsSuperCute(bool $isSuperCute): void
    {
        $this->isSuperCute = $isSuperCute;
    }

    /**
     * This method seems to be generated by the Phalcon\Model.
     * I wish I could figure out how to set up the database
     * @return array
     */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'age' => $this->age,
            'weight' => $this->weight,
            'gender' => $this->gender,
            'isCute' => $this->isSuperCute
        ];
    }


}